name: Python Flask CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Replace 'x' with the desired Python version (e.g., 3.7, 3.8, 3.9)

    - name: Install MySQL server
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server
        echo "[mysqld]" | sudo tee -a /etc/mysql/mysql.conf.d/mysqld.cnf
        echo "skip-grant-tables" | sudo tee -a /etc/mysql/mysql.conf.d/mysqld.cnf
        sudo service mysql restart
        sleep 5
        echo "UPDATE mysql.user SET authentication_string=PASSWORD('passwordis@2018') WHERE User='root';" | sudo mysql
        echo "FLUSH PRIVILEGES;" | sudo mysql
        sudo sed -i '/skip-grant-tables/d' /etc/mysql/mysql.conf.d/mysqld.cnf
        sudo service mysql restart
      continue-on-error: true

    - name: Install MySQL client for Python
      run: sudo apt-get install -y python3-dev libmysqlclient-dev

    - name: Install Python dependencies
      run: pip3 install -r requirements.txt

    - name: Run Flask application
      run: |
        python3 uat_app.py
